version: '3.3'
services:
  wls:
    image: weblogic-base-domain:10.3.6
    container_name: wls
    ports:
        - '7001:7001'
        - '5556:5556'
    volumes:
      - 'basedomain-data:/u01/oracle/weblogic/user_projects/domains/base_domain'
    environment: 
      - JAVA_OPTIONS=-javaagent:/u01/aspectjweaver-1.7.2.jar
volumes: 
  basedomain-data: